server:
  port: 2907

push:
  enabled: 'true'
  server: mein-server2

schedule:
  insert:
    enabled: 'false' # Scheduling Insert-Testdaten aktiv
    interval: 1ms # alle 2 Sekunden ein Insert machen

  worker:
    enabled: 'false' # Scheduling Pushen aktiv
    interval: 15m # Intervall, z.B. alle 15 Minuten sollen ...
    quantity: 10000 # maximal 1000 Aufträge verarbeitet werden
    start: '00:01' # Start-Zeit
    end: '23:59' # Ende-Zeit

spring:
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create
    task:
      scheduling:
        pool:
          size: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
